[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "lowresource-llm-evaluation"
version = "0.11.0.2"
description = "Métricas para evaluar LLMs en su capacidad de hablar una lengua sin datasets de Q&A"
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT"
requires-python = ">=3.10"

authors = [
    {name = "Miguel Gómez Prieto", email = "miguel.gprieto@alumnos.upm.es"}
]

keywords = ["evaluation", "machine learning", "utils", "LLM", "minority language", "benchmark", "analyze"]

dependencies = [
    "numpy",
    "pandas",
    "regex",
    "sacrebleu>=2.0",
    "python-Levenshtein",
    "groq"
]

[project.urls]
Homepage = "https://github.com/MiguelGP-13/TFG/tree/main/lowresource_llm_evaluation"

[tool.setuptools.packages.find]
where = ["."]
